# Generated by Django 2.2.dev20180829101932 on 2018-12-09 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='name', max_length=100)),
                ('lastname', models.CharField(default='lastname', max_length=100)),
                ('role', models.CharField(choices=[('student', 'student'), ('staff', 'staff'), ('teacher', 'teacher')], default='Student', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomname', models.CharField(default='roomname', max_length=100)),
                ('status', models.CharField(choices=[('available', 'available'), ('unavailable', 'unavailable'), ('pending', 'pending')], default='available', max_length=15)),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('slug', models.SlugField(default='roomname', max_length=100)),
                ('svgpath', models.CharField(default='PATH', max_length=3000)),
                ('floor', models.IntegerField(default=1)),
                ('note', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_of_reserve', models.CharField(default='reason', max_length=300)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('denied', 'denied')], default='pending', max_length=20)),
                ('teacher_result', models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('denied', 'denied')], default='pending', max_length=20)),
                ('staff_result', models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('denied', 'denied')], default='pending', max_length=20)),
                ('day_of_reserve', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration_begin', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration_end', models.DateTimeField(default=django.utils.timezone.now)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room', to='blog.room')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='blog.Employee')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to='blog.Employee')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='blog.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250, unique_for_date='publish')),
                ('body', models.TextField()),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-publish',),
            },
        ),
    ]
