# Generated by Django 2.2.dev20180829101932 on 2018-12-09 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='note',
        ),
    ]
