# Generated by Django 2.2.dev20180829101932 on 2018-12-09 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_room_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='note',
            field=models.CharField(default='', max_length=10),
        ),
    ]
