# Generated by Django 2.1.1 on 2018-10-02 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        migrations.AddField(
            model_name='employee',
            name='firstname',
            field=models.CharField(default='name', max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='lastname',
            field=models.CharField(default='lastname', max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(default='w', max_length=100),
        ),
    ]
