# Generated by Django 2.1.1 on 2018-10-02 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20181002_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('student', 'student'), ('staff', 'staff')], default='Student', max_length=100),
        ),
    ]
