# Generated by Django 2.1.1 on 2018-12-15 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_room_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reason_of_reserve',
            field=models.CharField(blank=True, default='reason', max_length=300),
        ),
    ]
