# Generated by Django 2.1.1 on 2018-10-05 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomname', models.CharField(default='roomname', max_length=100)),
                ('status', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='yes', max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('student', 'student'), ('staff', 'staff'), ('teacher', 'teacher')], default='Student', max_length=100),
        ),
    ]
