# Generated by Django 2.2.dev20180829101932 on 2018-12-17 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20181216_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reason_of_reserve',
            field=models.CharField(blank=True, default='reason', max_length=300),
        ),
    ]
