# Generated by Django 2.1.1 on 2018-10-05 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20181005_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='height',
            field=models.IntegerField(default=0),
        ),
    ]
