# Generated by Django 2.1.1 on 2018-10-05 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_room_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='width',
            field=models.IntegerField(default=0),
        ),
    ]
