# Generated by Django 2.2.dev20180829101932 on 2018-12-17 08:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_reservation_teacher_confirm_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='staff_confirm_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
