# Generated by Django 2.1.1 on 2018-10-05 03:54

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_room_width'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='room',
            managers=[
                ('q', django.db.models.manager.Manager()),
            ],
        ),
    ]
