# Generated by Django 2.2.dev20180829101932 on 2018-12-17 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_reservation_staff_confirm_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='staff_confirm_date',
            new_name='staff_approve_date',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='teacher_confirm_date',
            new_name='teacher_approve_date',
        ),
    ]
