# Generated by Django 2.1.1 on 2018-10-05 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20181005_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no'), ('pending', 'pending')], default='yes', max_length=10),
        ),
    ]
