# Generated by Django 2.2.dev20180829101932 on 2018-12-17 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20181217_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='teacher_approve_date',
            field=models.DateTimeField(default='Jan. 1, 1111, 1:11 a.m.'),
        ),
    ]
