# Generated by Django 2.2.dev20180829101932 on 2018-12-17 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20181217_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='staff_approve_date',
            field=models.DateTimeField(default='1111-01-01 01:11'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='teacher_approve_date',
            field=models.DateTimeField(default='1111-01-01 01:11'),
        ),
    ]
