# Generated by Django 2.1.2 on 2018-12-17 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20181218_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('available', 'available'), ('unavailable', 'unavailable'), ('pending', 'pending'), ('in progress', 'in progress')], default='available', max_length=15),
        ),
    ]
