# Generated by Django 2.1.1 on 2018-10-07 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='slug',
            field=models.SlugField(default='roomname', max_length=100),
        ),
    ]
