# Generated by Django 2.1.1 on 2018-10-07 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_room_slug'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='room',
            managers=[
            ],
        ),
    ]
