# Generated by Django 2.1.1 on 2018-10-07 10:39

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20181007_1736'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='reservation',
            managers=[
                ('objectsd', django.db.models.manager.Manager()),
            ],
        ),
    ]
