# Generated by Django 2.1.1 on 2018-10-07 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20181007_1739'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='reservation',
            managers=[
            ],
        ),
    ]
