# Generated by Django 2.1.1 on 2018-10-07 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20181007_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to='blog.Employee'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='blog.Employee'),
        ),
    ]
