# Generated by Django 2.1.1 on 2018-10-07 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20181007_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('denied', 'denied')], default='pending', max_length=10),
        ),
    ]
