# Generated by Django 2.1.1 on 2018-10-13 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20181007_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='svgpath',
            field=models.CharField(default='PATH', max_length=300),
        ),
    ]
