# Generated by Django 2.1.1 on 2018-10-13 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_room_svgpath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='svgpath',
            field=models.CharField(default='PATH', max_length=3000),
        ),
    ]
