# Generated by Django 2.2.dev20180829101932 on 2018-10-20 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_room_floor'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='blog.Employee'),
        ),
    ]
