# Generated by Django 2.2.dev20180829101932 on 2018-10-20 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_remove_reservation_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='staff',
            field=models.CharField(default='-', max_length=100),
        ),
    ]
