# Generated by Django 2.2.dev20180829101932 on 2018-10-20 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_reservation_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='staff',
        ),
    ]
