# Generated by Django 2.2.dev20180829101932 on 2018-10-22 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_reservation_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('accept-pending', 'accepted-pending'), ('denied', 'denied'), ('denied-pending', 'denied-pending')], default='pending', max_length=10),
        ),
    ]
