# Generated by Django 2.2.dev20180829101932 on 2018-10-24 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_auto_20181022_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reason_of_reserve',
            field=models.CharField(default='reason', max_length=300),
        ),
    ]
