# Generated by Django 2.1.2 on 2018-10-27 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_reservation_reason_of_reserve'),
        ('blog', '0033_reservation_reason_of_reserve'),
    ]

    operations = [
    ]
